AFRPAY-12265: better error message from response
JumiaPayAIG/woocommerce-plugin pull request #18
Opened 2022-10-16 10:50 UTC by ashrafhofney

2022-10-18 16:30 UTC, jmsakr approved these changes, later dismissed

2022-10-18 17:49 UTC, cacevedojumee requested changes
Please add unit testing for this method.
Thanks

2022-10-19 07:20 UTC, cacevedojumee approved these changes

2022-10-19 08:21 UTC, jmsakr approved these changes

2022-10-19 08:45 UTC, merged